### ISSUE TITLE
Fail to get dataset

### ISSUE THREAD

**Issue by flyflyly** [polkalian/THOR-EAE#1]
When I use the method you provided, I meet the following error:
<img width="518" alt="image" src="https://github.com/user-attachments/assets/b6eccc63-c0c7-4800-80ef-c754346c1514">
Could you provide another method to get the dataset, such as Google Drive, aliyun Drive, an so on. 
**And I think your work is very valuable for the development of embodied intelligence.** **Do you have any plans to open source the source code? Looking forward to your reply very much.**

**Comment by polkalian** [comment]
A new link to the dataset has been updated. Now you can download it from the Google Drive.

**Comment by flyflyly** [comment]
Thank you so much for uploading the dataset to Google Cloud Drive. But it seems that access to the dataset requires your authorization.
![Screenshot from 2024-10-17 17-57-23](https://github.com/user-attachments/assets/c4adb6b3-2e01-4f83-9054-4e224ff64b49)
